encoding: utf-8

# SEO相关信息
title: Geekie Blog
description: Stan的个人博客
keywords: Stan,Blog,Java,Go,Linux,SQL
author: Stan
footerText: ''

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://bruce-stark.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 仓库
    url: "https://github.com/Bruce-Stark/bruce-stark.github.io.git"

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false
